channel_app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'channel_app'
urlpatterns = [
    path('', views.home, name='home'),
    # path('chatapp/', views.chat, name='chat'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('login/', views.loginpage, name='login'),
    path('connect', views.connexion, name='connect'),
    path('deconnexion', views.deconnexion, name='deconnexion'),

]

tuto_channels/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('channel_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

channel_app/models.py
from django.db import models
# User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.


########################################## U T I L I S A T E U R ###########################################

class Utilisateur(models.Model):
    """Model definition for Utilisateur."""

    # TODO: Define fields here
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='utilisateur')
    photo = models.ImageField(upload_to='photo_utilisateur', default="profileimage.png", null = True, blank = True)
    

    statut = models.BooleanField(default=True)
    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)
    
    class Meta:
        """Meta definition for Utilisateur."""

        verbose_name = 'Utilisateur'
        verbose_name_plural = 'Utilisateurs'

    def __str__(self):
        """Unicode representation of Utilisateur."""
        return self.user.username

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Utilisateur.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, created, **kwargs):
            
        instance.utilisateur.save()

class Chat(models.Model):
    """Model definition for Chat."""

    # TODO: Define fields here
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='chatuser',blank=True, null=True)
    message = models.TextField()

    statut = models.BooleanField(default=True)
    date_add = models.DateTimeField(auto_now_add=True)
    date_upd = models.DateTimeField(auto_now=True)


    class Meta:
        """Meta definition for Chat."""

        verbose_name = 'Chat'
        verbose_name_plural = 'Chats'

    def __str__(self):
        """Unicode representation of Chat."""
        return self.user.username

    def last_10_messages():
        return Chat.objects.order_by('-date_add').all()[:10]

channel_app/views.py
from django.shortcuts import render

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import json
from django.utils.safestring import mark_safe
# Create your views here.




def home(request):

    data={}
    return render(request, 'home.html',data)

def chat(request):

    data={}
    return render(request, 'chats.html',data)

def loginpage(request):
    
    data={}
    return render(request, 'login.html',data)

@login_required
def room(request, room_name):
    
    data={
        'room_name': mark_safe(json.dumps(room_name)),
        'username': mark_safe(json.dumps(request.user.username)),
    }
    return render(request, 'chat.html',data)




def connexion(request):
    
    postdata = json.loads(request.body.decode('utf-8'))

    username = postdata['username']
    password = postdata['password']
    isSuccess=False

    user = authenticate(username=username, password=password)
    print(user)
    if user is not None and user.is_active :
        print("user is login")
        isSuccess = True
        login(request, user)
        datas = {
        'success':True,
        'username':username,
        'message':'Votre connection a reussi avec succes',
    }
        return JsonResponse(datas,safe=False) # page si connect
        
    else:
        data = {
        'success':False,
        'message':'Vos identifiants ne sont pas correcte',
        }
        return JsonResponse(data,safe=False)
    
    
    
    return JsonResponse(datas, safe=False)
    
    
    
    return JsonResponse(datas, safe=False)


def deconnexion(request):
    logout(request)
    return redirect('channel_app:home')
    

templates/chat.html
{% load static %}

<!DOCTYPE html><html class=''>
<!-- <head>
  <script src='//production-assets.codepen.io/assets/editor/live/console_runner-079c09a0e3b9ff743e39ee2d5637b9216b3545af0de366d4b9aad9dc87e26bfd.js'></script>
  <script src='//production-assets.codepen.io/assets/editor/live/events_runner-73716630c22bbc8cff4bd0f07b135f00a0bdc5d14629260c3ec49e5606f98fdd.js'></script>
  <script src='//production-assets.codepen.io/assets/editor/live/css_live_reload_init-2c0dc5167d60a5af3ee189d570b1835129687ea2a61bee3513dee3a50c115a77.js'></script> -->
  <meta charset='UTF-8'><meta name="robots" content="noindex"><link rel="shortcut icon" type="image/x-icon" href="//production-assets.codepen.io/assets/favicon/favicon-8ea04875e70c4b0bb41da869e81236e54394d63638a1ef12fa558a4a835f1164.ico" />
  <link rel="mask-icon" type="" href="//production-assets.codepen.io/assets/favicon/logo-pin-f2d2b6d2c61838f7e76325261b7195c27224080bc099486ddd6dccb469b8e8e6.svg" color="#111" />
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>


<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

<!------ Include the above in your HEAD tag ---------->




<script src="https://use.typekit.net/hoy3lrg.js"></script>
<script>try{Typekit.load({ async: true });}catch(e){}</script>
<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'><link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
<link rel="stylesheet" href="{% static 'style.css' %}"> 
</head>
<body>
<div id="apps">
<div id="frame">
	<div id="sidepanel">
		<div id="profile">
			<div class="wrap">
				<img id="profile-img" src="http://emilcarlsson.se/assets/mikeross.png" class="online" alt="" />
				<p>Mike Ross</p>
				<i class="fa fa-chevron-down expand-button" aria-hidden="true"></i>
				<div id="status-options">
					<ul>
						<li id="status-online" class="active"><span class="status-circle"></span> <p>Online</p></li>
						<li id="status-away"><span class="status-circle"></span> <p>Away</p></li>
						<li id="status-busy"><span class="status-circle"></span> <p>Busy</p></li>
						<li id="status-offline"><span class="status-circle"></span> <p>Offline</p></li>
					</ul>
				</div>
				<div id="expanded">
					<label for="twitter"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></label>
					<input name="twitter" type="text" value="mikeross" />
					<label for="twitter"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></label>
					<input name="twitter" type="text" value="ross81" />
					<label for="twitter"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></label>
					<input name="twitter" type="text" value="mike.ross" />
				</div>
			</div>
		</div>
		<div id="search">
			<label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
			<input type="text" placeholder="Search contacts..." />
		</div>
		<div id="contacts">
			<ul>
				<li class="contact">
					<div class="wrap">
						<span class="contact-status online"></span>
						<img src="http://emilcarlsson.se/assets/louislitt.png" alt="" />
						<div class="meta">
							<p class="name">Louis Litt</p>
							<p class="preview">You just got LITT up, Mike.</p>
						</div>
					</div>
				</li>
				<li class="contact active">
					<div class="wrap">
						<span class="contact-status busy"></span>
						<img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
						<div class="meta">
							<p class="name">Harvey Specter</p>
							<p class="preview">Wrong. You take the gun, or you pull out a bigger one. Or, you call their bluff. Or, you do any one of a hundred and forty six other things.</p>
						</div>
					</div>
				</li>
				
			</ul>
		</div>
		<div id="bottom-bar">
			<button id="addcontact"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> <span>Add contact</span></button>
			<button id="settings"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Settings</span></button>
		</div>
	</div>
	<div class="content">
		<div class="contact-profile">
			<img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
			<p>{{ username }}</p>
			<div class="social-media">
				<i class="fa fa-facebook" aria-hidden="true"></i>
				<i class="fa fa-twitter" aria-hidden="true"></i>
				 <i class="fa fa-instagram" aria-hidden="true"></i>
			</div>
		</div>
		<div class="messages">
			<ul id="chat-log">
					
				<li v-for="item in reponse" class="sent">
					<img src="http://emilcarlsson.se/assets/mikeross.png" alt="" />
					<p>${item}</p>
				</li>
				<li class="replies">
					<img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
					<p>When you're backed against the wall, break the god damn thing down.</p>
				</li>
				
			</ul>
		</div>
		<div class="message-input">
			<div class="wrap">
			<input v-model="message" type="text" placeholder="Write your message..." />

			<i class="fa fa-paperclip attachment" aria-hidden="true"></i>
			<button @click="sendmessage" class="submit"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
			</div>
		</div>
	</div>
</div>
</div>

<script src="{% static 'main.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/reconnecting-websocket@4.1.10/dist/reconnecting-websocket-cjs.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue-websocket@0.2.3/dist/vue-websocket.min.js"></script>

<script src='//production-assets.codepen.io/assets/common/stopExecutionOnTimeout-b2a7b3fe212eaa732349046d8416e00a9dec26eb7fd347590fbced3ab38af52e.js'></script>
<script src='https://code.jquery.com/jquery-2.2.4.min.js'></script>
<script>
	const app = new Vue({
        el: "#apps",
        data: {
            message: "",
            reponse: [],
            username:"Annonyme",
            date:'',
        

        },
        delimiters: ["${", "}"],
        mounted: function() {
            
            this.connect()
            this.username = '{{request.user.username}}';
            this.date = new Date().toLocaleString();
            
        },
        methods: {
           
            connect() {
                var roomName = {{room_name}};
                this.socket = new WebSocket('ws://127.0.0.1:8000/ws/chat/' + roomName + '/');
                this.socket.onopen = () => {
                    this.status = "connected";
                    console.log("connecte")
                    
                    this.socket.onmessage = ({data}) => {
                        
                    //   Recuperation message
                    wsdata = JSON.parse(data)
                    console.log(wsdata.message.mes)
                    this.reponse.push(wsdata.message) 
					console.log(this.reponse)
					
                    

                    
                    
                   
                    };
                };
            },
            disconnect() {
                this.socket.close();
                
                console.log("deconnecte")
            },
            
            
            sendmessage: function(){
                
                data = {
                    'message':{ 'mes':this.message,
                    'user':this.username },
                    
                }
                    this.socket.send(JSON.stringify(data));
                    
                    
                }
               
            },
              
            updateAdmin: function(){
                
                this.socket.send(JSON.stringify({ 'message':"code send succes", 'admin':this.admin, 'code':this.codedep }));

            }, 
            
                     
        
});
</script>

</body></html>

templates/chats.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat</title>
    <link rel="stylesheet" href="/static/css/main.css">
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    
</head>
<body>
    <hr>
    <hr>
    <button href=" {% url 'channel_app:deconnexion' %} ">Deconnexion</button>
    <div id="apps" class="col-sm-3 col-sm-offset-4 frame">
        
        <ul>
            <div v-for="item in reponse">
            <li style="width:100%">
                    
                <div v-if="item.user" class="msj macro">
                <div class="avatar"><img class="img-circle" style="width:100%;" /></div>
                    <div class="text text-l">
                        <p> ${item.user} </p>
                        <p> ${item.mes} </p>
                        <p><small>${date}</small></p> 
                    </div>
                </div>
            </li>
        </div>
        </ul>
        <div>
            <div class="msj-rta macro">                        
                <div class="text text-r" style="background:whitesmoke !important">
                    <input v-model="message" class="mytext" placeholder="Type a message"/>
                </div> 

            </div>
            <div style="padding:10px;">
                <span @click="sendmessage" class="glyphicon glyphicon-share-alt"></span>
            </div>                
        </div>
    </div>  

    <!-- <script src="/static/js/main.js"></script> -->
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/reconnecting-websocket@4.1.10/dist/reconnecting-websocket-cjs.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-websocket@0.2.3/dist/vue-websocket.min.js"></script>


    <script>
        const app = new Vue({
        el: "#apps",
        data: {
            message: "",
            reponse: [],
            username:"Annonyme",
            date:'',
        

        },
        delimiters: ["${", "}"],
        mounted: function() {
            
            this.connect()
            this.username = '{{request.user.username}}';
            this.date = new Date().toLocaleString();
            
        },
        methods: {
           
            connect() {
                roomName = "salon"
                this.socket = new WebSocket('ws://127.0.0.1:8000/ws/chat/' + roomName + '/');
                this.socket.onopen = () => {
                    this.status = "connected";
                    console.log("connecte")
                    
                    this.socket.onmessage = ({data}) => {
                        
                    //   Recuperation message
                    wsdata = JSON.parse(data)
                    console.log(wsdata.message.mes)
                    this.reponse.push(wsdata.message) 
                    console.log(this.reponse)
                    

                    
                    
                   
                    };
                };
            },
            disconnect() {
                this.socket.close();
                
                console.log("deconnecte")
            },
            
            
            sendmessage: function(){
                
                data = {
                    'message':{ 'mes':this.message,
                    'user':this.username },
                    
                }
                    this.socket.send(JSON.stringify(data));
                    
                    
                }
               
            },
              
            updateAdmin: function(){
                
                this.socket.send(JSON.stringify({ 'message':"code send succes", 'admin':this.admin, 'code':this.codedep }));

            }, 
            
                     
        
});
    </script>
</body>
</html>

templates/home.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django channels</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    
</head>
<body>
    <h1 style="text-align: center;">Django channels</h1>


    <div id="app">
        <ul>

            <li v-for='item in reponse'>
                ${item.user} : ${item.mes}
            </li>
            
        </ul>
        <input v-model="message" type="text" name="" id="">
        <input type="text"  v-model="username">
        <button @click="sendmessage" type="button" class="btn btn-primary">send message</button>
        
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue/2.5.17/vue.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/reconnecting-websocket@4.1.10/dist/reconnecting-websocket-cjs.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue-websocket@0.2.3/dist/vue-websocket.min.js"></script>

    <script>
        const app = new Vue({
            el: "#app",
            data: {
                message: "",
                reponse: [],
                username:"Annonyme",
            

            },
            delimiters: ["${", "}"],
            mounted: function() {
                
                this.connect()
                
            },
            methods: {
            
                connect() {
                    roomName = "hello"
                    this.socket = new WebSocket('ws://127.0.0.1:8000/ws/chat/' + roomName + '/');
                    this.socket.onopen = () => {
                        this.status = "connected";
                        console.log("connecte")
                        
                        this.socket.onmessage = ({data}) => {
                            
                        //   Recuperation message
                        wsdata = JSON.parse(data)
                        console.log(wsdata.message.mes)
                        this.reponse.push(wsdata.message)    
                        console.log(this.reponse)
                    
                        };
                    };
                },
                disconnect() {
                    this.socket.close();
                    
                    console.log("deconnecte")
                },
                
                
                sendmessage: function(){
                    
                    data = {
                        'message':{ 'mes':this.message,
                        'user':this.username }
                    }
                        this.socket.send(JSON.stringify(data));
                        
                        
                    }
                
                },
                
                updateAdmin: function(){
                    
                    this.socket.send(JSON.stringify({ 'message':"code send succes", 'admin':this.admin, 'code':this.codedep }));

                }, 
                
                        
            
    });
    </script>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>login</title>

        <!-- bootstrap lien -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

        <!-- VueJS et Axios -->
        <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
        <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

        <!-- css loader -->
        <style>
          .lds-ellipsis {
            display: inline-block;
            position: relative;
            width: 80px;
            height: 80px;
          }
          .lds-ellipsis div {
            position: absolute;
            top: 33px;
            width: 13px;
            height: 13px;
            border-radius: 50%;
            background: rgb(5, 5, 5);
            animation-timing-function: cubic-bezier(0, 1, 1, 0);
          }
          .lds-ellipsis div:nth-child(1) {
            left: 8px;
            animation: lds-ellipsis1 0.6s infinite;
          }
          .lds-ellipsis div:nth-child(2) {
            left: 8px;
            animation: lds-ellipsis2 0.6s infinite;
          }
          .lds-ellipsis div:nth-child(3) {
            left: 32px;
            animation: lds-ellipsis2 0.6s infinite;
          }
          .lds-ellipsis div:nth-child(4) {
            left: 56px;
            animation: lds-ellipsis3 0.6s infinite;
          }
          @keyframes lds-ellipsis1 {
            0% {
              transform: scale(0);
            }
            100% {
              transform: scale(1);
            }
          }
          @keyframes lds-ellipsis3 {
            0% {
              transform: scale(1);
            }
            100% {
              transform: scale(0);
            }
          }
          @keyframes lds-ellipsis2 {
            0% {
              transform: translate(0, 0);
            }
            100% {
              transform: translate(24px, 0);
            }
          }
          
        </style>
        
    </head>
    <body>
      <div id="test">
        <div class="general-box">
            <div class="form-box">
                <div class="form-header">
                    <div>
                        <h3>Connectez-vous</h3>
                    </div>       
                </div>
                <div class="form">
                  {% csrf_token %}
                  <div v-if="isSuccess" class="alert alert-success" role="alert">
                      ${ message }
                  </div>
                  <div  v-if="error" class="alert alert-danger" role="alert">
                      ${ message }
                  </div>
                    <input v-model="username" v-on:keyup.enter="login" type="email" placeholder="Entrer votre email" class="email-from">
                    <input v-model="password" v-on:keyup.enter="login" type="password" placeholder="Entrer votre mot de passe" class="password-from">
                    <button v-if="boutton" v-on:click="login" type="button" class="form-connexion"> connexion</button>
                    <div v-if="loader" class="lds-ellipsis"><div></div><div></div><div></div><div></div></div>
                    <!-- <div class="forgotten-password">
                        <a href="#" class="p-oublie">mot de passe oublié?</a>
                    </div> -->
                </div>
            </div>
        </div>
      </div>
    </body>
  <script>
    // Block Vue JS 
    new Vue({
          el: '#test',
          data: {
            username : '',
            password : '',
            loader : false,
            boutton : true,
            isSuccess : false,
            error : false,
            base_url : window.location.protocol + "//" + window.location.host + '/',
          
          },
          delimiters : [ "${", "}"],
          mounted(){
              
          },
          methods: {
            login:function(){
              this.loader = true
              this.boutton = false
              axios.defaults.xsrfCookieName = 'csrftoken'
                axios.defaults.xsrfHeaderName = 'X-CSRFToken'
                axios.post(this.base_url + 'connect', {
                    username: '' + this.username,
                    password: '' + this.password,
                    }).then(response => {
                        console.log(response) 
                        if(response.data.success){
                            this.isSuccess=true
                            this.error=false
                            this.loader = true
                            this.boutton = false
                            this.message=response.data.message
                            this.success=response.data.success
                            window.location.replace("indexAdmin");
                        }
                        else{
                          this.error=true
                          this.message=response.data.message
                          this.success=response.data.success
                          this.isSuccess=false
                          this.loader = false
                          this.boutton = true
                          this.password = ''
                        }
                        
                        console.log("success variable"+this.isSuccess)
                        // console.log("success variable"+this.error)
                    })
                    .catch((err) => {
                        console.log(err);
                        
                    })
            },
          }
      });
  
  </script>
</html>

templates/room.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}


    <script src="https://cdn.jsdelivr.net/npm/reconnecting-websocket@4.1.10/dist/reconnecting-websocket-cjs.min.js"></script>
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new ReconnectingWebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'command': 'new_message'
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>